//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować niewłaściwe zachowanie i zostaną utracone
//     w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShipmentsStatus.Infrastructure.DpdReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class Exception
    {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class customerEventDataV2
    {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class customerEventV2
    {
        
        private string businessCodeField;
        
        private string countryField;
        
        private string depotField;
        
        private string descriptionField;
        
        private customerEventDataV2[] eventDataListField;
        
        private string eventTimeField;
        
        private long idField;
        
        private long objectIdField;
        
        private string operationTypeField;
        
        private string packageReferenceField;
        
        private string parcelReferenceField;
        
        private string waybillField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string businessCode
        {
            get
            {
                return this.businessCodeField;
            }
            set
            {
                this.businessCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string depot
        {
            get
            {
                return this.depotField;
            }
            set
            {
                this.depotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventDataList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public customerEventDataV2[] eventDataList
        {
            get
            {
                return this.eventDataListField;
            }
            set
            {
                this.eventDataListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string eventTime
        {
            get
            {
                return this.eventTimeField;
            }
            set
            {
                this.eventTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long objectId
        {
            get
            {
                return this.objectIdField;
            }
            set
            {
                this.objectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string operationType
        {
            get
            {
                return this.operationTypeField;
            }
            set
            {
                this.operationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string packageReference
        {
            get
            {
                return this.packageReferenceField;
            }
            set
            {
                this.packageReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string parcelReference
        {
            get
            {
                return this.parcelReferenceField;
            }
            set
            {
                this.parcelReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string waybill
        {
            get
            {
                return this.waybillField;
            }
            set
            {
                this.waybillField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class customerEventsResponseV2
    {
        
        private string confirmIdField;
        
        private customerEventV2[] eventsListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string confirmId
        {
            get
            {
                return this.confirmIdField;
            }
            set
            {
                this.confirmIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventsList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public customerEventV2[] eventsList
        {
            get
            {
                return this.eventsListField;
            }
            set
            {
                this.eventsListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class authDataV1
    {
        
        private string channelField;
        
        private string loginField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string channel
        {
            get
            {
                return this.channelField;
            }
            set
            {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string login
        {
            get
            {
                return this.loginField;
            }
            set
            {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", ConfigurationName="ShipmentsStatus.Infrastructure.DpdReference.DPDInfoServicesObjEvents")]
    public interface DPDInfoServicesObjEvents
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/getEventsForCus" +
            "tomerV4Request", ReplyAction="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/getEventsForCus" +
            "tomerV4Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(ShipmentsStatus.Infrastructure.DpdReference.Exception), Action="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/getEventsForCus" +
            "tomerV4/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV4Response> getEventsForCustomerV4Async(ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV4Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/getEventsForWay" +
            "billV1Request", ReplyAction="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/getEventsForWay" +
            "billV1Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(ShipmentsStatus.Infrastructure.DpdReference.Exception), Action="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/getEventsForWay" +
            "billV1/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.getEventsForWaybillV1Response> getEventsForWaybillV1Async(ShipmentsStatus.Infrastructure.DpdReference.getEventsForWaybillV1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/markEventsAsPro" +
            "cessedV1Request", ReplyAction="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/markEventsAsPro" +
            "cessedV1Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(ShipmentsStatus.Infrastructure.DpdReference.Exception), Action="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/markEventsAsPro" +
            "cessedV1/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.markEventsAsProcessedV1Response> markEventsAsProcessedV1Async(ShipmentsStatus.Infrastructure.DpdReference.markEventsAsProcessedV1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/getEventsForCus" +
            "tomerV1Request", ReplyAction="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/getEventsForCus" +
            "tomerV1Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(ShipmentsStatus.Infrastructure.DpdReference.Exception), Action="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/getEventsForCus" +
            "tomerV1/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV1Response> getEventsForCustomerV1Async(ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/getEventsForCus" +
            "tomerV2Request", ReplyAction="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/getEventsForCus" +
            "tomerV2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(ShipmentsStatus.Infrastructure.DpdReference.Exception), Action="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/getEventsForCus" +
            "tomerV2/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV2Response> getEventsForCustomerV2Async(ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/getEventsForCus" +
            "tomerV3Request", ReplyAction="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/getEventsForCus" +
            "tomerV3Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(ShipmentsStatus.Infrastructure.DpdReference.Exception), Action="http://events.dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEvents/getEventsForCus" +
            "tomerV3/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV3Response> getEventsForCustomerV3Async(ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV3Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForCustomerV4", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForCustomerV4Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1;
        
        public getEventsForCustomerV4Request()
        {
        }
        
        public getEventsForCustomerV4Request(int limit, string language, ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1)
        {
            this.limit = limit;
            this.language = language;
            this.authDataV1 = authDataV1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForCustomerV4Response", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForCustomerV4Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShipmentsStatus.Infrastructure.DpdReference.customerEventsResponseV2 @return;
        
        public getEventsForCustomerV4Response()
        {
        }
        
        public getEventsForCustomerV4Response(ShipmentsStatus.Infrastructure.DpdReference.customerEventsResponseV2 @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public enum eventsSelectTypeEnum
    {
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        ONLY_LAST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class customerEventsResponseV3
    {
        
        private string confirmIdField;
        
        private customerEventV3[] eventsListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string confirmId
        {
            get
            {
                return this.confirmIdField;
            }
            set
            {
                this.confirmIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventsList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public customerEventV3[] eventsList
        {
            get
            {
                return this.eventsListField;
            }
            set
            {
                this.eventsListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class customerEventV3
    {
        
        private string businessCodeField;
        
        private string countryField;
        
        private string depotField;
        
        private string depotNameField;
        
        private string descriptionField;
        
        private customerEventDataV3[] eventDataListField;
        
        private string eventTimeField;
        
        private long objectIdField;
        
        private string packageReferenceField;
        
        private string parcelReferenceField;
        
        private string waybillField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string businessCode
        {
            get
            {
                return this.businessCodeField;
            }
            set
            {
                this.businessCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string depot
        {
            get
            {
                return this.depotField;
            }
            set
            {
                this.depotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string depotName
        {
            get
            {
                return this.depotNameField;
            }
            set
            {
                this.depotNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventDataList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public customerEventDataV3[] eventDataList
        {
            get
            {
                return this.eventDataListField;
            }
            set
            {
                this.eventDataListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string eventTime
        {
            get
            {
                return this.eventTimeField;
            }
            set
            {
                this.eventTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long objectId
        {
            get
            {
                return this.objectIdField;
            }
            set
            {
                this.objectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string packageReference
        {
            get
            {
                return this.packageReferenceField;
            }
            set
            {
                this.packageReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string parcelReference
        {
            get
            {
                return this.parcelReferenceField;
            }
            set
            {
                this.parcelReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string waybill
        {
            get
            {
                return this.waybillField;
            }
            set
            {
                this.waybillField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class customerEventDataV3
    {
        
        private string codeField;
        
        private string descriptionField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForWaybillV1", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForWaybillV1Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string waybill;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShipmentsStatus.Infrastructure.DpdReference.eventsSelectTypeEnum eventsSelectType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1;
        
        public getEventsForWaybillV1Request()
        {
        }
        
        public getEventsForWaybillV1Request(string waybill, ShipmentsStatus.Infrastructure.DpdReference.eventsSelectTypeEnum eventsSelectType, string language, ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1)
        {
            this.waybill = waybill;
            this.eventsSelectType = eventsSelectType;
            this.language = language;
            this.authDataV1 = authDataV1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForWaybillV1Response", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForWaybillV1Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShipmentsStatus.Infrastructure.DpdReference.customerEventsResponseV3 @return;
        
        public getEventsForWaybillV1Response()
        {
        }
        
        public getEventsForWaybillV1Response(ShipmentsStatus.Infrastructure.DpdReference.customerEventsResponseV3 @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="markEventsAsProcessedV1", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class markEventsAsProcessedV1Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string confirmId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1;
        
        public markEventsAsProcessedV1Request()
        {
        }
        
        public markEventsAsProcessedV1Request(string confirmId, ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1)
        {
            this.confirmId = confirmId;
            this.authDataV1 = authDataV1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="markEventsAsProcessedV1Response", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class markEventsAsProcessedV1Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public markEventsAsProcessedV1Response()
        {
        }
        
        public markEventsAsProcessedV1Response(bool @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class customerEventsResponseV1
    {
        
        private string confirmIdField;
        
        private customerEventV1[] eventsListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string confirmId
        {
            get
            {
                return this.confirmIdField;
            }
            set
            {
                this.confirmIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eventsList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public customerEventV1[] eventsList
        {
            get
            {
                return this.eventsListField;
            }
            set
            {
                this.eventsListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/")]
    public partial class customerEventV1
    {
        
        private string businessCodeField;
        
        private string countryField;
        
        private string depotField;
        
        private string descriptionField;
        
        private string eventData1Field;
        
        private string eventData2Field;
        
        private string eventData3Field;
        
        private string eventTimeField;
        
        private long idField;
        
        private long objectIdField;
        
        private string operationTypeField;
        
        private string packageReferenceField;
        
        private string parcelReferenceField;
        
        private string waybillField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string businessCode
        {
            get
            {
                return this.businessCodeField;
            }
            set
            {
                this.businessCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string depot
        {
            get
            {
                return this.depotField;
            }
            set
            {
                this.depotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string eventData1
        {
            get
            {
                return this.eventData1Field;
            }
            set
            {
                this.eventData1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string eventData2
        {
            get
            {
                return this.eventData2Field;
            }
            set
            {
                this.eventData2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string eventData3
        {
            get
            {
                return this.eventData3Field;
            }
            set
            {
                this.eventData3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string eventTime
        {
            get
            {
                return this.eventTimeField;
            }
            set
            {
                this.eventTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public long objectId
        {
            get
            {
                return this.objectIdField;
            }
            set
            {
                this.objectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string operationType
        {
            get
            {
                return this.operationTypeField;
            }
            set
            {
                this.operationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string packageReference
        {
            get
            {
                return this.packageReferenceField;
            }
            set
            {
                this.packageReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string parcelReference
        {
            get
            {
                return this.parcelReferenceField;
            }
            set
            {
                this.parcelReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string waybill
        {
            get
            {
                return this.waybillField;
            }
            set
            {
                this.waybillField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForCustomerV1", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForCustomerV1Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1;
        
        public getEventsForCustomerV1Request()
        {
        }
        
        public getEventsForCustomerV1Request(int limit, ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1)
        {
            this.limit = limit;
            this.authDataV1 = authDataV1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForCustomerV1Response", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForCustomerV1Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShipmentsStatus.Infrastructure.DpdReference.customerEventsResponseV1 @return;
        
        public getEventsForCustomerV1Response()
        {
        }
        
        public getEventsForCustomerV1Response(ShipmentsStatus.Infrastructure.DpdReference.customerEventsResponseV1 @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForCustomerV2", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForCustomerV2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1;
        
        public getEventsForCustomerV2Request()
        {
        }
        
        public getEventsForCustomerV2Request(int limit, string language, ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1)
        {
            this.limit = limit;
            this.language = language;
            this.authDataV1 = authDataV1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForCustomerV2Response", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForCustomerV2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShipmentsStatus.Infrastructure.DpdReference.customerEventsResponseV1 @return;
        
        public getEventsForCustomerV2Response()
        {
        }
        
        public getEventsForCustomerV2Response(ShipmentsStatus.Infrastructure.DpdReference.customerEventsResponseV1 @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForCustomerV3", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForCustomerV3Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1;
        
        public getEventsForCustomerV3Request()
        {
        }
        
        public getEventsForCustomerV3Request(int limit, ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1)
        {
            this.limit = limit;
            this.authDataV1 = authDataV1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getEventsForCustomerV3Response", WrapperNamespace="http://events.dpdinfoservices.dpd.com.pl/", IsWrapped=true)]
    public partial class getEventsForCustomerV3Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://events.dpdinfoservices.dpd.com.pl/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ShipmentsStatus.Infrastructure.DpdReference.customerEventsResponseV2 @return;
        
        public getEventsForCustomerV3Response()
        {
        }
        
        public getEventsForCustomerV3Response(ShipmentsStatus.Infrastructure.DpdReference.customerEventsResponseV2 @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface DPDInfoServicesObjEventsChannel : ShipmentsStatus.Infrastructure.DpdReference.DPDInfoServicesObjEvents, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class DPDInfoServicesObjEventsClient : System.ServiceModel.ClientBase<ShipmentsStatus.Infrastructure.DpdReference.DPDInfoServicesObjEvents>, ShipmentsStatus.Infrastructure.DpdReference.DPDInfoServicesObjEvents
    {
        
        /// <summary>
        /// Wdróż tę metodę częściową, aby skonfigurować punkt końcowy usługi.
        /// </summary>
        /// <param name="serviceEndpoint">Punkt końcowy do skonfigurowania</param>
        /// <param name="clientCredentials">Poświadczenia klienta</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DPDInfoServicesObjEventsClient() : 
                base(DPDInfoServicesObjEventsClient.GetDefaultBinding(), DPDInfoServicesObjEventsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DPDInfoServicesObjEventsPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DPDInfoServicesObjEventsClient(EndpointConfiguration endpointConfiguration) : 
                base(DPDInfoServicesObjEventsClient.GetBindingForEndpoint(endpointConfiguration), DPDInfoServicesObjEventsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DPDInfoServicesObjEventsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DPDInfoServicesObjEventsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DPDInfoServicesObjEventsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DPDInfoServicesObjEventsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DPDInfoServicesObjEventsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV4Response> ShipmentsStatus.Infrastructure.DpdReference.DPDInfoServicesObjEvents.getEventsForCustomerV4Async(ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV4Request request)
        {
            return base.Channel.getEventsForCustomerV4Async(request);
        }
        
        public System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV4Response> getEventsForCustomerV4Async(int limit, string language, ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1)
        {
            ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV4Request inValue = new ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV4Request();
            inValue.limit = limit;
            inValue.language = language;
            inValue.authDataV1 = authDataV1;
            return ((ShipmentsStatus.Infrastructure.DpdReference.DPDInfoServicesObjEvents)(this)).getEventsForCustomerV4Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.getEventsForWaybillV1Response> ShipmentsStatus.Infrastructure.DpdReference.DPDInfoServicesObjEvents.getEventsForWaybillV1Async(ShipmentsStatus.Infrastructure.DpdReference.getEventsForWaybillV1Request request)
        {
            return base.Channel.getEventsForWaybillV1Async(request);
        }
        
        public System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.getEventsForWaybillV1Response> getEventsForWaybillV1Async(string waybill, ShipmentsStatus.Infrastructure.DpdReference.eventsSelectTypeEnum eventsSelectType, string language, ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1)
        {
            ShipmentsStatus.Infrastructure.DpdReference.getEventsForWaybillV1Request inValue = new ShipmentsStatus.Infrastructure.DpdReference.getEventsForWaybillV1Request();
            inValue.waybill = waybill;
            inValue.eventsSelectType = eventsSelectType;
            inValue.language = language;
            inValue.authDataV1 = authDataV1;
            return ((ShipmentsStatus.Infrastructure.DpdReference.DPDInfoServicesObjEvents)(this)).getEventsForWaybillV1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.markEventsAsProcessedV1Response> ShipmentsStatus.Infrastructure.DpdReference.DPDInfoServicesObjEvents.markEventsAsProcessedV1Async(ShipmentsStatus.Infrastructure.DpdReference.markEventsAsProcessedV1Request request)
        {
            return base.Channel.markEventsAsProcessedV1Async(request);
        }
        
        public System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.markEventsAsProcessedV1Response> markEventsAsProcessedV1Async(string confirmId, ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1)
        {
            ShipmentsStatus.Infrastructure.DpdReference.markEventsAsProcessedV1Request inValue = new ShipmentsStatus.Infrastructure.DpdReference.markEventsAsProcessedV1Request();
            inValue.confirmId = confirmId;
            inValue.authDataV1 = authDataV1;
            return ((ShipmentsStatus.Infrastructure.DpdReference.DPDInfoServicesObjEvents)(this)).markEventsAsProcessedV1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV1Response> ShipmentsStatus.Infrastructure.DpdReference.DPDInfoServicesObjEvents.getEventsForCustomerV1Async(ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV1Request request)
        {
            return base.Channel.getEventsForCustomerV1Async(request);
        }
        
        public System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV1Response> getEventsForCustomerV1Async(int limit, ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1)
        {
            ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV1Request inValue = new ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV1Request();
            inValue.limit = limit;
            inValue.authDataV1 = authDataV1;
            return ((ShipmentsStatus.Infrastructure.DpdReference.DPDInfoServicesObjEvents)(this)).getEventsForCustomerV1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV2Response> ShipmentsStatus.Infrastructure.DpdReference.DPDInfoServicesObjEvents.getEventsForCustomerV2Async(ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV2Request request)
        {
            return base.Channel.getEventsForCustomerV2Async(request);
        }
        
        public System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV2Response> getEventsForCustomerV2Async(int limit, string language, ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1)
        {
            ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV2Request inValue = new ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV2Request();
            inValue.limit = limit;
            inValue.language = language;
            inValue.authDataV1 = authDataV1;
            return ((ShipmentsStatus.Infrastructure.DpdReference.DPDInfoServicesObjEvents)(this)).getEventsForCustomerV2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV3Response> ShipmentsStatus.Infrastructure.DpdReference.DPDInfoServicesObjEvents.getEventsForCustomerV3Async(ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV3Request request)
        {
            return base.Channel.getEventsForCustomerV3Async(request);
        }
        
        public System.Threading.Tasks.Task<ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV3Response> getEventsForCustomerV3Async(int limit, ShipmentsStatus.Infrastructure.DpdReference.authDataV1 authDataV1)
        {
            ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV3Request inValue = new ShipmentsStatus.Infrastructure.DpdReference.getEventsForCustomerV3Request();
            inValue.limit = limit;
            inValue.authDataV1 = authDataV1;
            return ((ShipmentsStatus.Infrastructure.DpdReference.DPDInfoServicesObjEvents)(this)).getEventsForCustomerV3Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DPDInfoServicesObjEventsPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DPDInfoServicesObjEventsPort))
            {
                return new System.ServiceModel.EndpointAddress("https://dpdinfoservices.dpd.com.pl/DPDInfoServicesObjEventsService/DPDInfoService" +
                        "sObjEvents");
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DPDInfoServicesObjEventsClient.GetBindingForEndpoint(EndpointConfiguration.DPDInfoServicesObjEventsPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DPDInfoServicesObjEventsClient.GetEndpointAddress(EndpointConfiguration.DPDInfoServicesObjEventsPort);
        }
        
        public enum EndpointConfiguration
        {
            
            DPDInfoServicesObjEventsPort,
        }
    }
}
